### ISSUE TITLE
Search drop down is broken in develop

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#133] opened 2016-04-26 21:42 UTC
@alexgreen @kidcompassion Any ideas on this:
<img width="1372" alt="_pennies_for_billions___aboriginals_fight_near_giveaway_of_pipeline_rights_in_1952___the_tyee" src="https://cloud.githubusercontent.com/assets/34128/14835121/05350560-0bbd-11e6-9d99-e393601459ee.png">

cc @MrBryan

**Comment by alexgreen** [comment] 2016-04-27 11:31
I'll have a look. Could be that some recent css I wrote was scoped too broadly.

**Comment by alexgreen** [comment] 2016-04-27 15:07
Had a quick look. It's not affected by my css. This is a problem caused by the introduction of the rule that limits the width of the primary nav:

```
@media (min-width: 1200px)
.primary-nav {
    max-width: 1200px;
    margin: 0 auto;
}
```

I believe this rule was added to fix the nav bar spacing and prevent the logo from getting too big. So this will need to be addressed in the context of #128 (so I'm assigning to MrBryan).

In the meantime I've added
`.search-block .dropdown-menu, .search-block .dropdown-menu .navbar-form {
  max-width: 1200px;
}
`
which seems to fix it. But this isn't a good solution —the nav bar is getting crufty with several layers of patches now and should get refactored.

**Comment by phillipadsmith** [comment] 2016-05-13 00:03
@MrBryan @alexgreen So, it appears that this search input issue and one other are all that remains to be done to close [this milestone](https://github.com/TheTyee/design-article.thetyee.ca/milestones/Q&A,%20browser%20testing,%20etc.%20%28April%208-17%29%20). 

I believe you're each assigned one. 

Would you be able to commit to closing these two issues by the end of the week?

**Comment by MrBryan** [comment] 2016-05-13 04:38
sorry i really stink at github, yes I'll have a crack tomorrow at knocking off anything assigned to me

**Comment by MrBryan** [comment] 2016-05-13 05:02
I assume the issue is that it is too far down ? It appears that the margin rule applied to 

```
.search-block .dropdown-menu, .search-block .dropdown-menu .navbar-form
margin: 18px 0px 0px 0px;
```

is what causes that and it fixes it through all widths to remove it. Just want to be sure I understood the issue.  as the  primary-nav {  max-width: 1200px; doesn't affect anything that I can notice at first glance

![image](https://cloud.githubusercontent.com/assets/1721891/15238410/bfd344d2-18a5-11e6-9ea8-9e44924c877e.png)

**Comment by MrBryan** [comment] 2016-05-13 05:03
sorry that was padding and margin removed - this is just margin

![image](https://cloud.githubusercontent.com/assets/1721891/15238498/80bdd824-18a6-11e6-9b23-fad0dec5669c.png)

**Comment by MrBryan** [comment] 2016-05-13 05:10
with margin top explicitly 0 rather than just disabling the 18px rule: 

![image](https://cloud.githubusercontent.com/assets/1721891/15238579/79b6500a-18a7-11e6-9632-e4d22e8cf3c8.png)

**Comment by MrBryan** [comment] 2016-05-13 05:34
fixed .. i'll assume  8c2087be657be89f0e3878499769c894dfb7a1f6

**Comment by alexgreen** [comment] 2016-05-13 15:13
> I assume the issue is that it is too far down ?

No, if you look at Phillip's screenshot you'll see that the problem is that the submit button breaks the layout and gets pushed off screen in wider viewports. I think that's the problem he meant. As I mentioned above, I identified the recently-introduced max-width property as the cause. 
As I test it now, the submit button no longer seems to break the layout, but _something_ in the search dropdown form **is** forcing the page to expand horizontally, and it happens at the 1200px breakpoint. See attached.

![screen shot 2016-05-13 at 11 58 00 pm](https://cloud.githubusercontent.com/assets/151099/15252339/4c278d86-1968-11e6-9338-46bda89227b7.png)

**Comment by alexgreen** [comment] 2016-05-13 15:45
I'm guessing that Sally set that top margin to prevent the search form from covering up parts of logo and nav borders in narrow views, which is what happens now:

![screen shot 2016-05-14 at 12 43 39 am](https://cloud.githubusercontent.com/assets/151099/15253417/257782d6-196d-11e6-8b8a-eac6c34b95b2.png)

**Comment by MrBryan** [comment] 2016-05-13 16:46
ok addressed both of those. Can't reproduce the search breaking on another line but i do see that it was larger than screen width so limited it to 1200px too seems to solve.  And added the margin back in for screens less than 990px

7260b8fcd87f434aa4cffd60566a40640eeb77ca
dc6da8ea2dbdb4a38ba681be4d54ae4bd06d04a3

![image](https://cloud.githubusercontent.com/assets/1721891/15255151/4d51b462-1908-11e6-8e63-12bd53951a37.png)

**Comment by alexgreen** [comment] 2016-05-13 17:28
It's still breaking the layout in Chrome.

![screen shot 2016-05-14 at 2 26 45 am](https://cloud.githubusercontent.com/assets/151099/15256233/88b36136-197b-11e6-9dc1-4d70837302b9.png)

**Comment by alexgreen** [comment] 2016-05-13 17:33
Oh, sorry it is fixed. For some reason only your add margin back commit got pulled.

**Closed as completed by alexgreen** 2016-05-13 17:33 UTC
Labels: Status: Bug, Type: Front end; CSS & presentation
