### ISSUE TITLE
Image float is breaking a paragraph

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#333] opened 2016-08-11 17:24 UTC
http://thetyee.ca/News/2016/08/10/Faulty-Towers-Commercial-Drive/

Didn't seem 100% like an existing issue.

Over to @alexgreen first.

**Comment by alexgreen** [comment] 2016-08-17 07:02
This appears to be caused by

```
.figure--xl, .figure--xl {
    clear: right;
    float: left;
    padding-top: 0;
}

```

(hmm I see an unrelated typo in the selector)

It's entirely possible that we may have to let a figure--xl break paragraphs occasionally when it's in proximity with an aside.

The figure--xl needs to float left to prevent collisions with asides.
Omitting the the clear right does seem to solve the problem in this case, but I'd have to do some more comprehensive testing to ensure that it doesn't cause other problems elsewhere.

**Comment by alexgreen** [comment] 2016-08-17 07:20
see also https://basecamp.com/1929296/projects/9481270/messages/60476230#comment_446108155

**Comment by phillipadsmith** [comment] 2016-08-29 17:29
Any thoughts / updates, @alexgreen

**Comment by alexgreen** [comment] 2016-09-14 06:18
Seems like we only have 2 examples of this issue:
http://thetyee.ca/Culture/2016/07/15/New-Glimpses-of-Fighting-Fascists/  (but the issue only shows up in medium viewports)
http://thetyee.ca/News/2016/08/10/Faulty-Towers-Commercial-Drive/

I have a solution that will fix one of them, but without further test cases it's hard to evaluate.

**Comment by alexgreen** [comment] 2016-09-16 01:13
I just pushed a fix for this. afdbf4140a072ec877d271f8411697784182c2f8
It seems to correct every example I've been given at almost every viewport width. (On osx Chrome anyway -- once it's previewed we can test on other browsers.) However all but 2 of the examples were ads, not editorial photos, so I don't know if it will have the same success rate for fixing the problem in photo cases.

**Closed as completed** 2022-01-04 20:00 UTC
Labels: Status: Bug, Type: Front end; CSS & presentation, Status: fixed; awaiting deployment, Priority: Medium
