### ISSUE TITLE
Series articles not using correct Tyee series box

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#311] opened 2016-07-18 07:16 UTC
Some stories are still not using the correct series box. e.g.:
http://preview.thetyee.ca/News/2012/07/04/CarbonFootprint/

**Comment by MrBryan** [comment] 2016-07-27 21:06
was caused by series master story not being republished yet. Fixed in production and should be for all stories as publishing finishes   http://thetyee.ca/News/2012/07/04/CarbonFootprint/

**Closed as completed by MrBryan** 2016-07-27 21:06 UTC
Labels: Status: Bug, Type: Front end; CSS & presentation, Priority: Immediate
