### ISSUE TITLE
Style slideshow object

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#45] opened 2016-03-23 15:17 UTC
- [ ] Create design for slideshow
- [ ] Style slideshow for all views

**Comment by kidcompassion** [comment] 2016-03-23 15:38
I can do this! Do you have a design for it? If not that's okay too, I can leave it for you to design in browser, no worries.

**Comment by alexgreen** [comment] 2016-03-23 16:31
I don't believe this was ever included in the design mockups.

**Comment by kidcompassion** [comment] 2016-03-23 20:40
okey doke, will leave for you to do then.

**Comment by phillipadsmith** [comment] 2016-03-31 19:55
> I don't believe this was ever included in the design mockups.

I see a slideshow in the mock-up article. Is that not as intended? 

Either way, I feel we can move this to a later milestone (and will do so for now).

**Comment by alexgreen** [comment] 2016-04-01 11:04
You mean this?
This is just a placeholder. I think we'd need to add more controls for a slideshow, at least a back button. But I do like the idea of a slideshow with a soundtrack. Such immersive!

![screen shot 2016-04-01 at 8 00 26 pm](https://cloud.githubusercontent.com/assets/151099/14205218/9e29d598-f844-11e5-8ab3-30057f5fae96.png)

**Comment by phillipadsmith** [comment] 2016-04-04 20:29
I was referring to this (which might be gone now?):
<img width="669" alt="the_tyee_article_page" src="https://cloud.githubusercontent.com/assets/34128/14262208/243ec30c-fa69-11e5-9f42-f00b9b85de4b.png">

**Comment by alexgreen** [comment] 2016-04-05 16:32
Oh, I think those controls are still from the initial boilerplate. I commented out that slideshow until there's time to style it, but then someone brought it back.

**Comment by kidcompassion** [comment] 2016-04-05 18:17
The slideshow that is there was one I had done without a design, so very little thought went into it. It could use some <3!

**Comment by phillipadsmith** [comment] 2016-04-21 19:37
@alexgreen @kidcompassion Can we use Bootstrap's carousel library for this? E.g., http://getbootstrap.com/2.3.2/javascript.html#carousel

**Comment by alexgreen** [comment] 2016-04-22 16:51
Yes, let's do that. Will probably have to adjust those enormous labels, but it's pretty close.

**Comment by phillipadsmith** [comment] 2016-04-25 07:55
> Yes, let's do that. Will probably have to adjust those enormous labels, but it's pretty close.

Assigning to @MrBryan, unless you're already working on it @alexgreen?

**Comment by alexgreen** [comment] 2016-04-25 11:56
I think this will probably be quicker for me to do as it should only involve writing the html include and applying a little css. I can put it on my list for after #41 and #83

**Comment by phillipadsmith** [comment] 2016-04-26 19:49
> I think this will probably be quicker for me to do as it should only involve writing the html include and applying a little css. 

👍

**Comment by phillipadsmith** [comment] 2016-04-28 22:54
See also #134

**Comment by alexgreen** [comment] 2016-05-03 10:26
I've built and styled the slideshow object. 

I've set it not to auto cycle. (Slides only advance when the reader clicks.) Because the slides are sometimes different sizes this causes the slideshow container to expand and contract pushing any text below it up and down in a pretty distracting way, so I thought it's best if that doesn't happen continually. (You can see this happening in the older Tyee slideshows too, e.g. http://preview.thetyee.ca/News/2014/12/05/Affordable-Homeownership-Experiments/index.html# )

**Comment by alexgreen** [comment] 2016-05-03 10:29
@phillipadsmith do you think there will be any need to put a slideshow into an aside?

One possibility that comes to mind is we could use an aside carousel to cycle through a series of related articles. But that sounds like something for the future.

**Comment by phillipadsmith** [comment] 2016-05-05 19:02
> @phillipadsmith do you think there will be any need to put a slideshow into an aside?

Can't imagine a scenario for that, no.

> One possibility that comes to mind is we could use an aside carousel to cycle through a series of related articles. But that sounds like something for the future.

Agreed.

> I've set it not to auto cycle. (Slides only advance when the reader clicks.) Because the slides are sometimes different sizes this causes the slideshow container to expand and contract pushing any text below it up and down in a pretty distracting way, so I thought it's best if that doesn't happen continually. (You can see this happening in the older Tyee slideshows too, e.g. http://preview.thetyee.ca/News/2014/12/05/Affordable-Homeownership-Experiments/index.html# )

Great. Look forward to checking it out today.

**Comment by phillipadsmith** [comment] 2016-05-06 01:15
Looks great. Used this in #134. Closing this for now.

**Closed as completed by phillipadsmith** 2016-05-06 01:15 UTC

**Comment by alexgreen** [comment] 2016-05-10 16:44
> One possibility that comes to mind is we could use an aside carousel to cycle through a series of related articles. But that sounds like something for the future.
> 
> Agreed.

I was actually talking about putting this carousel of related articles into an aside. (So that a bunch of related articles can be shown without cluttering the column.)

**Comment by phillipadsmith** [comment] 2016-05-11 05:07
> I was actually talking about putting this carousel of related articles into an aside. (So that a bunch of related articles can be shown without cluttering the column.)

Hmmm... interesting idea. Let's leave it on the "circle back later" list for now.
