### ISSUE TITLE
Latest stories : finish styling

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#145] opened 2016-05-03 14:49 UTC
I'm not sure who's currently in charge of the latest stories block, but there's a few things that still need to get fixed.
- [x] text is too small (see original mockup attached)
- [x] photo is too wide, aspect ratio should remain constant so image doesn't cropped too drastically, because the width of the story items doesn't remain constant this issue is more pronounced in some viewports than in others (see second image below) 
- [x] in narrow views the photo breaks the layout
- [x] in bottom-of-column position, latest stories header is missing
- [x] in bottom-of-col position, borders above and below are missing
- [x] in bottom-of-col position, in narrow views the latest-stories block should be aligned with (and same width as) the main text col. The .main-col-container class may be able to help with that.
- [x] `li`s are irregular in height and this causes weird borders heights. `li`s should be the full height of the `ul` at views of 768px and wider. 

.
![5-lateststories-draft5-wide](https://cloud.githubusercontent.com/assets/151099/14986945/e98a5fb4-1188-11e6-83a9-147a3f2338a7.jpg)

---

![screen shot 2016-05-05 at 4 49 32 pm](https://cloud.githubusercontent.com/assets/151099/15038743/6ae75b8a-12e1-11e6-9a9f-03d57f95d1a1.png)

**Comment by phillipadsmith** [comment] 2016-05-05 19:03
Assigning @MrBryan because he's been fixing the image size issue to address parts of this.

**Comment by alexgreen** [comment] 2016-05-26 13:05
@MrBryan How are things going with this item? Does it seem doable? Do you have time for this or should we reassign?

**Comment by phillipadsmith** [comment] 2016-05-30 06:02
I've re-ping @MrBryan via e-mail just in case he's not seen this thread.

**Comment by MrBryan** [comment] 2016-06-10 23:25
c56a36e 8b70dd3

**Comment by MrBryan** [comment] 2016-06-10 23:27
Looks good now to me. Can't reproduce the image "breaking" any thing in smaller layouts.

**Comment by MrBryan** [comment] 2016-06-11 03:17
I added a thumbnail that will be preferred by this widget .. will appear as new stories are published or old republished.  One thing to add when going live is a check that the chosen thumbnail is available already on the server because there is a lag between being added to API and existing on filesystem. I commented that out in here because it breaks when x-domain

**Comment by alexgreen** [comment] 2016-06-11 09:45
In views narrower than 768px it breaks the layout because it doesn't conform to the correct column width:

![screen shot 2016-06-11 at 6 41 58 pm](https://cloud.githubusercontent.com/assets/151099/15984402/9484ee68-3004-11e6-8c6c-be214c921642.png)

**Comment by alexgreen** [comment] 2016-06-11 09:47
As noted above, 

> text is too small (see original mockup attached).

I'll adjust this, but probably won't have any time over the weekend.

**Comment by MrBryan** [comment] 2016-06-17 23:59
Moving this to post launch - the border heights aren't a big deal

**Comment by MrBryan** [comment] 2016-08-04 15:47
Fixed this here 995d7624660279fb7d0eb6b0fcb9fac95fe840a5

**Comment by alexgreen** [comment] 2016-08-05 08:47
Still has odd styling in views narrower than 768px (as mentioned above with screenshot): 
• it doesn't conform to the correct column width
• wrong text colour

**Comment by MrBryan** [comment] 2016-08-08 22:45
K did those

https://github.com/TheTyee/design-article.thetyee.ca/commit/9e830c008861f312da3508d0cdc27cb289f7120f

https://github.com/TheTyee/design-article.thetyee.ca/commit/401485c71516f734df98885e0698a4717464e4cf

**Closed as completed by MrBryan** 2016-08-08 22:45 UTC
Labels: Status: Bug, Type: Front end; CSS & presentation
