### ISSUE TITLE
prevent collision between ads and asides in medium views

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#92] opened 2016-03-30 19:27 UTC

**Comment by phillipadsmith** [comment] 2016-07-08 00:32
Seems that this is still an issue?

**Comment by phillipadsmith** [comment] 2016-07-08 00:32
Ad running into series box
URL: http://preview.thetyee.ca/Culture/2014/12/29/Off-Grid-In-Canada/
Description: The half-page ad runs into the series box on this story, may be happening on others?
Reporter: Robyn
<img width="244" alt="tyee_staff_consolidated_article_page_feedback_-_google_docs" src="https://cloud.githubusercontent.com/assets/34128/16674029/cd7d6380-4468-11e6-8723-3dde4b5a4151.png">

**Comment by MrBryan** [comment] 2016-07-11 21:01
Can't reproduce, tried in mac & PC Firefox+Chrome.. anyone else?  possibly a css change fixed already

**Comment by phillipadsmith** [comment] 2016-07-11 21:15
> Can't reproduce, tried in mac & PC Firefox+Chrome.. anyone else? possibly a css change fixed already

Looking good. Closing for now.

**Closed as completed by phillipadsmith** 2016-07-11 21:15 UTC
