### ISSUE TITLE
Fix issue relating to advertising zone includes

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#85] opened 2016-03-28 22:09 UTC
Hey @alexgreen,

I've swapped out the placeholder images for actual Google DFP advertising delivery in the `feature/advertising` branch. I've followed the pattern of passing the ad-zone tag as a parameter to the include. 

One problem that's now visible is the impact of a double big box ad on the vertical spacing of the story:

<img width="1012" alt="localhost_4000" src="https://cloud.githubusercontent.com/assets/34128/14091775/19c0494a-f4f7-11e5-874a-19a356c71442.png">

The other issue is that I'm not sure any ads are getting trafficked to the 'Tyee_Upper_BigBox' zone (which I've used in the fallback position for the first ad, so avoid the delivery of a 300x600 ad in that location). I'll ask Michelle about this tomorrow.

Phillip.

**Comment by alexgreen** [comment] 2016-03-29 11:21
> double big box ad

It sounds like you mean a "half-page ad". Up until now our design brief said there would only be leaderboard ads and bigbox (300x250) ads. None other. I'm still amazed that Michelle agreed to this, but there you have it! There will be no more half-page ads in the Tyee. historic milestone in marketing!

**Comment by phillipadsmith** [comment] 2016-03-31 17:35
> It sounds like you mean a "half-page ad". Up until now our design brief said there would only be leaderboard ads and bigbox (300x250) ads. None other. I'm still amazed that Michelle agreed to this, but there you have it! There will be no more half-page ads in the Tyee. historic milestone in marketing!

Do you have a reference to this conversation, @alexgreen. 

Our understand is that the half page will be visible on desktop, and not on mobile.

**Comment by alexgreen** [comment] 2016-03-31 17:48
Yeah here it is in the brief, dating back to at least 9 July 2015:
https://basecamp.com/1929296/projects/9481270/documents/9054108

> Big box ad zone, as well as enough space around it to let it breath and not feel "busy." Treat it like real content. ﻿NO OTHER AD FORMATS.

I confirmed this several times, including at a general meeting, because it totally blew my mind that all other ad formats are being dropped.

**Comment by phillipadsmith** [comment] 2016-03-31 17:59
> I confirmed this several times, including at a general meeting, because it totally blew my mind that all other ad formats are being dropped.

Thanks for that, Alex. I'll check-in with Michelle on this again today.

**Comment by phillipadsmith** [comment] 2016-03-31 19:22
Hi @alexgreen,

Final word from Michelle, regardless of previous interpretations:
- Half page ad will need to appear on desktop views in the upper right position
- There should _always_ be two big box zones in the story, not just when the half-page ad is showing
- The first big box should automatically appear after paragraph five (and can be manually re-positioned from there if needed)
- The second "lower" big box can stay where it is

I'm going to e-mail The Tyee's advertising service provider today and determine if we'll prevent the half-page ad delivery at the DFP (ad server) level, or with some browser/viewport sniffing on the server or client -- obviously, we don't want to deliver an ad unit that is not visible as it would negatively impact stats for that unit.

@alexgreen If you can prioritize making these adjustments for the end of this week / Monday, that would be greatly appreciated, as we're aiming to ask "Tyee friends & family" for feedback early next week.

**Comment by phillipadsmith** [comment] 2016-04-01 01:08
> I'm going to e-mail The Tyee's advertising service provider today and determine if we'll prevent the half-page ad delivery at the DFP (ad server) level, or with some browser/viewport sniffing on the server or client -- obviously, we don't want to deliver an ad unit that is not visible as it would negatively impact stats for that unit.

E-mail sent. Waiting for response.

**Comment by alexgreen** [comment] 2016-04-01 12:41
> Half page ad will need to appear on desktop views in the upper right position

This is a problem because in the current design and css a half-page ad will not fit next to the featured image/media. (—the featured image and neighbouring ad are not within the flow of the article content, so expanding this section vertically will create a gap in the layout.) So this will require some reworking and might not be possible for monday. 

> There should always be two big box zones in the story, not just when the half-page ad is showing

I'm not understanding this. (There currently _are_ 2 bigbox images in the prototype.)
To clarify:
- There should always be 2 bigbox ads, one after paragraph 5, another crics 6 paragraphs before the end.
- In addition there will (often) be a half-page ad that appears only on "desktop" views. This ad must appear to the right of the article's featured image.

Is that correct?

I have an idea for how this can work but it will likely only be possible for viewports that are at least 1275px wide. Is that ok?

**Comment by phillipadsmith** [comment] 2016-04-04 20:38
> This is a problem because in the current design and css a half-page ad will not fit next to the featured image/media. (—the featured image and neighbouring ad are not within the flow of the article content, so expanding this section vertically will create a gap in the layout.) So this will require some reworking and might not be possible for monday.

Understood. I think we'll leave the placeholder ads for Monday's preview vs. running the live ads from the advertising server.

> I'm not understanding this. (There currently are 2 bigbox images in the prototype.)

There are actually **three** currently: but two of them pretend to be one via media queries, e.g., on desktop, the big box shows up to the right of the media, yet at small views the ad that's about three paragraphs in is revealed, and the other is hidden (or vice-versa). 

The difference in what Michelle is requesting is that there should always be two big boxes within the story flow, regardless of the view port size. So, to be clear: three ads visible at larger screen sizes, and two (in the story flow) at smaller sizes. Currently, it's always two that are visible. 

So:

> There should always be 2 bigbox ads, one after paragraph 5, another crics 6 paragraphs before the end.

Correct.

> In addition there will (often) be a half-page ad that appears only on "desktop" views. This ad must appear to the right of the article's featured image.

An ad should _always_ be visible in that location: sometimes big box, sometimes full page, depending on what is being delivered by the server in that moment.

> I have an idea for how this can work but it will likely only be possible for viewports that are at least 1275px wide. Is that ok?

If that covers off most "desktop" scenarios these days, then I believe so yes.

**Comment by alexgreen** [comment] 2016-04-05 16:51
Holy moly! After so much discussion, commenting and briefing about ads I can't believe we're only now getting the specs straight. Well, better late than never I guess.

> but two of them pretend to be one via media queries

Aha! My understanding was that they ARE one and the same ad that changes position based on screen size.

Thanks for the clarification. Just one question:

> sometimes full page

full page? Please tell me we're not talking about yet another ad format besides bigbox and half-page.

**Comment by phillipadsmith** [comment] 2016-04-05 17:45
> full page? Please tell me we're not talking about yet another ad format besides bigbox and half-page.

Half page! Whoops!

**Comment by alexgreen** [comment] 2016-04-14 14:29
Oh, I thought I'd closed this issue already. It's done, as I mentioned in #100 (with the > 1400px caveat)

**Closed as completed** 2016-04-14 14:29 UTC
Labels: Status: Bug
