### ISSUE TITLE
Video captions / credits are floating oddly on small viewports

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#215] opened 2016-06-28 21:49 UTC
http://preview.thetyee.ca/News/2016/05/05/Fleeing-For-McMurray/

Something odd going on here:
<img width="348" alt="iphone_5s_-_iphone_5s___ios_9_3__13e230_" src="https://cloud.githubusercontent.com/assets/34128/16433518/82096bb8-3d3f-11e6-9d18-3f6ebe8e639d.png">

**Comment by alexgreen** [comment] 2016-06-29 19:33
...not to mention that the video is breaking the layout.

The problem is those videos aren't getting marked up correctly. The video is sitting in a `<p>` and the caption is in a `<blockquote>`. That's causing incorrect styling to be applied in all browser views.

All media objects should be marked up inside a figure, and use a figcaption.
When in doubt see http://thetyee.github.io/design-article.thetyee.ca/library

**Comment by MrBryan** [comment] 2016-07-04 05:36
same as #214 fixed by detecting in-body iframes (hopefully this will catch other cases - as long as iframe precedes the blockquote as with here)

**Closed as completed by MrBryan** 2016-07-04 05:36 UTC

**Comment by alexgreen** [comment] 2016-07-08 05:46
Why was this issue occurring in the first place?
Is it because staff were embedding videos and formatting the captions manually (and in this case someone had decided to put the caption into a blockquote)?

—oh sorry, I see there's already a discussion of this in #214
